### ISSUE TITLE
Project Presentation

### ISSUE THREAD

**Issue by Red-Two** [amm4108/AngleGators#12]
Create Final Presentation for HFOSS Course

**Comment by Aalaizah** [comment]
- [x] Demonstration
- [x] How does the code work(best pieces)
- [x] Worst pieces of software
- [x] Stumbling Blocks
- [x] Successes
- [x] What would you have done differently
- [x] Future?

I think we should each pick one success/stumbling block, and one best/worst piece of the program to use for the presentation, that way not any one person is doing the work.
