### ISSUE TITLE
Conveyor Belt

### ISSUE THREAD

**Issue by Aalaizah** [amm4108/AngleGators#17]
- [ ] Objects move down the belt
- [ ] Objects can be moved to the other conveyor belt
- [x] Text Above Items that show the Angle Needed

**Comment by Aalaizah** [comment]
I just realized that we don't have any way of showing what angle is needed, so we should have some sort of text that travels with the object.

**Comment by Aalaizah** [comment]
It also might be easier if we just say the mouth has to be closed for things that are too big, instead of a second conveyor belt, sine we're coming down to the wire

**Comment by mellolikejello** [comment]
scrapping conveyor belt, flow down the river instead!
